cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('remove/<int:pack_id>', views.remove, name='remove'),
    path('add/<int:pack_id>', views.add, name='add'),
    path('adjust/<int:pack_id>/<str:change>', views.adjust, name='adjust'),
    path('', views.detail, name='detail')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
import category.views as category
import product.views as product
import home.views as home
import cart.views as cart

admin.site.site_header = 'My admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('i18n/', include('django.conf.urls.i18n')),
    #path('', include('home.urls')),
]
urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('home.urls')),
    path('search/', home.search, name='search'),
    path('category/<category>', category.index),
    path('products/all/', product.all, name='all_products'),
    path('product/<product>', product.index),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    #path('checkout/', cart.checkout, name='checkout'),
    url('checkout/', RedirectView.as_view(url='http://google.com'), name='checkout'),
    prefix_default_language=True,
)

product/models.py
from django.db import models
import uuid

CONTAINER_TYPE = (
    ('bottle', 'bottle'),
    ('cap', 'cap'),
    ('cream', 'cream'),
    ('inhaler', 'inhaler'),
    ('pack', 'pack'),
    ('pill', 'pill'),
    ('sachet', 'sachet'),
    ('spray', 'spray'),
    ('tab', 'tab'),
    ('tablet', 'tablet'),
    ('tube', 'tube'),
)

MEASURE = (
    ('mcg', 'mcg'),
    ('mg', 'mg'),
    ('g', 'g'),
)

class Product(models.Model):
    named_id = models.SlugField(primary_key=True)
    is_active = models.BooleanField()
    is_brand = models.BooleanField()
    is_sale = models.BooleanField(default=False)
    is_new = models.BooleanField(default=False)
    container_type = models.CharField(max_length=10, choices=CONTAINER_TYPE)
    per_item = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.named_id

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class ProductCategory(models.Model):
    product_id = models.ForeignKey('Product', on_delete=models.CASCADE)
    category_id = models.ForeignKey('category.Category', on_delete=models.CASCADE)


class ProductGeneric(models.Model):
    product_id = models.ForeignKey('Product', on_delete=models.CASCADE)
    generic_id = models.ForeignKey('generic_name.GenericName', on_delete=models.CASCADE)


def get_uid():
    return uuid.uuid4().hex[:8]


class Pack(models.Model):
    uid = models.CharField(max_length=8, editable=False, unique=True, default=get_uid)
    product_id = models.ForeignKey('Product', on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    dosage = models.DecimalField(max_digits=6, decimal_places=2)
    measure = models.CharField(max_length=10, choices=MEASURE)
    quantity = models.PositiveSmallIntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)

product/views.py
from django.shortcuts import render
from django.http import Http404
from django.core.paginator import Paginator, InvalidPage
from product.models import Product, ProductGeneric, Pack
from cart.forms import CartAddPackForm


def index(request, product):
    product_name = product
    try:
        product = Product.objects.get(named_id=product)
    except Product.DoesNotExist:
        raise Http404

    generic = list()
    try:
        query = ProductGeneric.objects.filter(product_id=product)
        for item in query:
            generic.append(str(item.generic_id))
    except ProductGeneric.DoesNotExist:
        pass

    try:
        pack = Pack.objects.filter(product_id=product)
    except Pack.DoesNotExists:
        raise Http404

    cart_pack_form = CartAddPackForm()

    return render(request, 'product/index.html', locals())


def all(request):
    all_product = Product.objects.all()
    try:
        page_num = request.GET['page']
    except KeyError:
        page_num = 1

    paginator = Paginator(all_product, 12)

    try:
        products = paginator.page(page_num)
    except InvalidPage:
        products = paginator.page(1)

    return render(request, 'product/all.html', locals())

templates/default/product/all.html
{% extends '__base.html' %}
{% block header %}
    {% include '_header.html' %}
{% endblock %}
{% load static %}
{% load i18n %}
{% block content %}
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
                    {% block left_sidebar %}
                        {% include '_left_sidebar.html' %}
                    {% endblock %}
				</div>

				<div class="col-sm-9 padding-right">
         			<div class="breadcrumbs">
                        <ol class="breadcrumb">
                          <li><a href="{% url 'index' %}">Home</a></li>
                          <li class="active">All Products</li>
                        </ol>
			        </div>
                    <h2 class="title text-center">PRODUCTS</h2>
                        {% for product in products %}
                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                        <div class="productinfo text-center">
                                            <img src="{{ STATIC_URL }}product/{{ product.named_id|lower }}.png" alt="" />
                                            <h2>${{ product.per_item|floatformat:2 }}</h2>
                                            <p>{% trans product.named_id context 'products' %}</p>
                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>{% trans 'Add to cart' %}</a>
                                        </div>
                                        <div class="product-overlay">
                                            <div class="overlay-content">
                                                <h2>${{ product.per_item|floatformat:2 }}</h2>
                                                <p>{% trans product.named_id context 'products' %}</p>
                                                <a href="/{{LANGUAGE_CODE}}/product/{{ product.named_id }}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>{% trans 'Add to cart' %}</a>
                                            </div>
                                        </div>
                                </div>
                                {% if product.is_sale %}
                                    <img src="{% static 'default/images/home/sale.png' %}" class="new" alt="" />
                                {% endif %}
                                {% if product.is_new %}
                                    <img src="{% static 'default/images/home/new.png' %}" class="new" alt="" />
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}

                        <div class="pagination">
                            <span class="step-links">
                                {% if products.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ products.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ products.number }} of {{ products.paginator.num_pages }}.
                                </span>

                                {% if products.has_next %}
                                    <a href="?page={{ products.next_page_number }}">next</a>
                                    <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>

				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block footer %}
    {% include '_footer.html' %}
{% endblock %}

templates/default/product/index.html
{% extends '__base.html' %}
{% block header %}
    {% include '_header.html' %}
{% endblock %}
{% block content %}
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
                    {% block left_sidebar %}
                        {% include '_left_sidebar.html' %}
                    {% endblock %}
				</div>

				<div class="col-sm-9 padding-right">
                    {% block features_items %}
                        {% include 'product/product.html' %}
                    {% endblock %}

                    {% block bestsellers %}
                        {% include '_bestsellers.html' %}
                    {% endblock %}
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block footer %}
    {% include '_footer.html' %}
{% endblock %}

templates/default/product/product.html
{% load static %}
{% load i18n %}
{% block product %}
    <div class="product-details"><!--product-details-->
        <div class="col-sm-5">
            <div class="view-product">
                <img src="{{ STATIC_URL }}product/{{ product.named_id|lower }}.png" alt="" />
                <h3>ZOOM</h3>
            </div>
        </div>
        <div class="col-sm-7">
            <div class="product-information"><!--/product-information-->
                <h2>{% trans product.named_id context 'products' %}</h2>
                {% if generic %}
                    <p><b>Brand:</b> {% for item in generic %}{% trans item context 'generic' %}{% endfor %}</p>
                {% endif %}
                <span>
                {% for p in pack %}
                    <p>
                        <b>{% trans product.named_id context 'products' %}</b> {{ p.dosage }}{{ p.measure }} x {{ p.quantity }} {{ product.container_type}} = ${{ p.price }}
                        <form action="{% url "cart:add" p.id %}" method="post">
                            {% csrf_token %}
                            {{ cart_pack_form }}
                	        <button type="submit" class="btn btn-fefault cart">
							    <i class="fa fa-shopping-cart"></i>
								{% trans 'Add to cart' %}
                            </button>
                        </form>
                    </p>
                {% endfor %}
                </span>
                <p><b>Availability:</b> In Stock</p>
                <p><b>Condition:</b> New</p>
            </div><!--/product-information-->
        </div>

        <div class="category-tab shop-details-tab"><!--category-tab-->
            <div class="col-sm-12">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#details" data-toggle="tab">Details</a></li>
                    <li><a href="#details2" data-toggle="tab">Details 2</a></li>
                    <li><a href="#details3" data-toggle="tab">Details 3</a></li>
                </ul>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade active in" id="details" >
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aliquid cum dicta doloribus eveniet neque nulla odit, quasi, qui saepe, similique sint voluptatum. Autem consequatur dolor, eos est eveniet ex harum id in iure laboriosam magnam modi neque officia pariatur possimus quae quam quis soluta tempora tenetur ullam vero vitae.
                </div>

                <div class="tab-pane fade" id="details2" >
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, assumenda aut debitis et impedit magni maiores nam quis unde velit. Assumenda at cumque enim, esse ipsum iusto laboriosam nam natus nostrum obcaecati, praesentium sunt unde. Eaque porro quibusdam recusandae saepe suscipit. Adipisci debitis dicta id magni mollitia, nam nihil pariatur quam qui saepe? Ab adipisci amet aperiam consequuntur cumque dolore, doloremque dolores eligendi eos error esse exercitationem expedita labore libero minima modi natus nemo odit omnis quaerat quam quas quibusdam quidem repellendus repudiandae similique sint sit tempore totam veritatis! Dolor quae qui sapiente vitae? Dolorem est illum molestiae nulla quaerat.
                </div>

                <div class="tab-pane fade" id="details3" >
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium distinctio ducimus ea exercitationem facere inventore, neque quis quo ratione. Accusamus adipisci at, cum cumque dicta eligendi eos eveniet explicabo natus, porro provident quos, ratione sequi soluta totam. Aliquid debitis ex fugiat laboriosam maxime necessitatibus nihil numquam quae quod vel! Aliquam, aliquid amet aspernatur atque autem consectetur cum debitis error est labore nulla numquam perferendis quae quam recusandae sequi ut? Aperiam aspernatur dolores iusto minus non possimus quas, quasi voluptatum. Facere labore, voluptas? Aliquid amet beatae blanditiis dolores eius expedita fuga inventore nam, nisi nobis non perferendis praesentium quasi quia quibusdam quis quos ratione repellat sequi, sit temporibus veritatis, voluptates voluptatibus. A accusantium ad adipisci culpa cum, doloremque eius est eum ex in maxime nemo neque odio qui, ratione repellat voluptatem. Ad adipisci autem commodi consectetur debitis delectus deleniti deserunt distinctio, dolorum ducimus eius est, fuga, harum nesciunt quae quis quisquam reiciendis sint sit temporibus. A alias aliquam amet asperiores at beatae eaque earum exercitationem, fugiat in ipsam iste itaque iure minima nesciunt optio, perspiciatis quaerat qui ratione repellat repellendus, saepe tempora ut voluptatem voluptatibus. Blanditiis deserunt distinctio eligendi explicabo facilis in incidunt inventore iste laborum pariatur porro qui tempora, veniam!
                </div>
            </div>
        </div><!--/category-tab-->

    </div><!--/product-details-->
{% endblock %}