cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('remove/<int:pack_id>', views.remove, name='remove'),
    path('add/<int:pack_id>', views.add, name='add'),
    path('adjust/<int:pack_id>/<str:change>', views.adjust, name='adjust'),
    path('', views.detail, name='detail')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
import category.views as category
import product.views as product
import home.views as home
import cart.views as cart

admin.site.site_header = 'My admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('i18n/', include('django.conf.urls.i18n')),
    #path('', include('home.urls')),
]
urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('home.urls')),
    path('search/', home.search, name='search'),
    path('category/<category>', category.index),
    path('products/all/', product.all, name='all_products'),
    path('product/<product>', product.index),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    #path('checkout/', cart.checkout, name='checkout'),
    url('checkout/', RedirectView.as_view(url='http://google.com'), name='checkout'),
    prefix_default_language=True,
)

cart/models.py
#from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PACK_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddPackForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PACK_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Pack
from .cart import Cart
from .forms import CartAddPackForm


@require_POST
def add(request, pack_id):
    cart = Cart(request)
    pack = get_object_or_404(Pack, id=pack_id)
    form = CartAddPackForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(pack=pack, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:detail')


def remove(request, pack_id):
    cart = Cart(request)
    pack = get_object_or_404(Pack, id=pack_id)
    cart.remove(pack)
    return redirect('cart:detail')


def adjust(request, pack_id, change):
    cart = Cart(request)
    pack = get_object_or_404(Pack, id=pack_id)
    quantity = 1
    if change == '-':
        quantity = -1
    cart.adjust(pack=pack, quantity=quantity)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    if cart:
        return render(request, 'cart/detail.html', locals())
    else:
        return render(request, 'cart/empty.html')


def checkout(request):
    cart = Cart(request)
    if cart:
        return render(request, 'cart/checkout.html', {'cart': cart})
    else:
        return render(request, 'cart/empty.html')

templates/default/cart/checkout.html
checkout

templates/default/cart/detail.html
{% extends '__base.html' %}
{% block header %}
    {% include '_header.html' %}
{% endblock %}
{% load static %}
{% load i18n %}
{% block content %}
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
                    {% block left_sidebar %}
                        {% include '_left_sidebar.html' %}
                    {% endblock %}
				</div>

				<div class="col-sm-9 padding-right">
         			<div class="breadcrumbs">
                        <ol class="breadcrumb">
                          <li><a href="{% url 'index' %}">Home</a></li>
                          <li class="active">Shopping Cart</li>
                        </ol>
			        </div>
                    <h2 class="title text-center">CART DETAILS</h2>
                    <section id="cart_items">
                        <div class="table-responsive cart_info">
                            <table class="table table-condensed">
                                <thead>
                                    <tr class="cart_menu">
                                        <td class="image">Item</td>
                                        <td class="description"></td>
                                        <td class="price">Price</td>
                                        <td class="quantity">Quantity</td>
                                        <td class="total">Total</td>
                                        <td></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                        {% with pack=item.pack %}
                                            <tr>
                                                <td class="cart_product">
                                                    <a href=""><img src="{{ STATIC_URL }}product/{{ pack.product_id|lower }}.png" alt=""></a>
                                                </td>
                                                <td class="cart_description">
                                                    <h4><a href="">{% trans pack.product_id.named_id context 'products' %}</a></h4>
                                                    <p>{{ pack.dosage }}{{ pack.measure }} x {{ pack.quantity }} {{ pack.product_id.container_type}}</p>
                                                </td>
                                                <td class="cart_price">
                                                    <p>${{ item.price }}</p>
                                                </td>
                                                <td class="cart_quantity">
                                                    <div class="cart_quantity_button">
                                                        <a class="cart_quantity_up" href="{% url "cart:adjust" pack.id "+" %}"> + </a>
                                                        <input class="cart_quantity_input" type="text" name="quantity" value="{{ item.quantity }}" autocomplete="off" size="2" readonly>
                                                        <a class="cart_quantity_down" href="{% url "cart:adjust" pack.id "-" %}"> - </a>
                                                    </div>
                                                </td>
                                                <td class="cart_total">
                                                    <p class="cart_total_price">${{ item.total_price }}</p>
                                                </td>
                                                <td class="cart_delete">
                                                    <a class="cart_quantity_delete" href="{% url "cart:remove" pack.id %}"><i class="fa fa-times"></i></a>
                                                </td>
                                            </tr>
                                        {% endwith %}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </section>

                    <div>
                        <div class="total_area">
                            <ul>
                                <li>Total <span>${{ cart.get_total_price }}</span></li>
                            </ul>
                            <a class="btn btn-default continue" href="{% url 'all_products' %}">Continue shopping</a>

						    <a class="btn btn-default check_out" href="{% url 'checkout' %}">Checkout</a>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block footer %}
    {% include '_footer.html' %}
{% endblock %}

templates/default/cart/empty.html
{% extends '__base.html' %}
{% block header %}
    {% include '_header.html' %}
{% endblock %}
{% load static %}
{% load i18n %}
{% block content %}
	<section>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    {% block left_sidebar %}
                        {% include '_left_sidebar.html' %}
                    {% endblock %}
                </div>
                <div class="col-sm-9 padding-right">
                    <div class="breadcrumbs">
                        <ol class="breadcrumb">
                          <li><a href="{% url 'index' %}">Home</a></li>
                          <li class="active">Shopping Cart</li>
                        </ol>
                    </div>
                    <h2 class="title text-center">CART DETAILS</h2>
                    <h3>Basket is empty</h3>
                    <a class="btn btn-default continue" href="{% url 'all_products' %}">Continue shopping</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block footer %}
    {% include '_footer.html' %}
{% endblock %}