cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('remove/<int:pack_id>', views.remove, name='remove'),
    path('add/<int:pack_id>', views.add, name='add'),
    path('adjust/<int:pack_id>/<str:change>', views.adjust, name='adjust'),
    path('', views.detail, name='detail')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import RedirectView
import category.views as category
import product.views as product
import home.views as home
import cart.views as cart

admin.site.site_header = 'My admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('i18n/', include('django.conf.urls.i18n')),
    #path('', include('home.urls')),
]
urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('home.urls')),
    path('search/', home.search, name='search'),
    path('category/<category>', category.index),
    path('products/all/', product.all, name='all_products'),
    path('product/<product>', product.index),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    #path('checkout/', cart.checkout, name='checkout'),
    url('checkout/', RedirectView.as_view(url='http://google.com'), name='checkout'),
    prefix_default_language=True,
)

templates/default/__base.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{{ title }}{% endblock %}</title>
    {% block stylesheet %}
        <link href="{% static 'default/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'default/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'default/css/prettyPhoto.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'default/css/price-range.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'default/css/animate.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'default/css/main.css' %}" rel="stylesheet" type="text/css">
    {% endblock %}
    {% block responsive %}
        <link href="{% static 'default/css/responsive.css' %}" rel="stylesheet" type="text/css">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="{% static 'default/images/ico/favicon.ico' %}">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'default/images/ico/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'default/images/ico/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'default/images/ico/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'default/images/ico/apple-touch-icon-57-precomposed.png' %}">
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    {% block slider %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
    {% block scripts %}
        <script src="{% static 'default/js/vue.min.js' %}"></script>
        <script src="{% static 'default/js/jquery.js' %}"></script>
	    <script src="{% static 'default/js/bootstrap.min.js' %}"></script>
	    <script src="{% static 'default/js/jquery.scrollUp.min.js' %}"></script>
	    <script src="{% static 'default/js/price-range.js' %}"></script>
        <script src="{% static 'default/js/jquery.prettyPhoto.js' %}"></script>
        <script src="{% static 'default/js/main.js' %}"></script>
    {% endblock %}
</body>
</html>

templates/default/_bestsellers.html
{% load static %}
{% load i18n %}
{% get_static_prefix as STATIC_PREFIX %}
{% load chunkify %}
{% block bestsellers %}
	<div class="recommended_items"><!--recommended_items-->
		<h2 class="title text-center">{% trans 'bestsellers' %}</h2>
		<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner">
				{% with bestsellers|chunk_list:3 as chunks %}
					{% for chunk in chunks %}
						<div class="item {% if forloop.first %} active {% endif %}">
							{% for product in chunk %}
								<div class="col-sm-4">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="{{ STATIC_PREFIX }}product/{{ product.named_id|lower }}.png" alt="" />
												<h2>${{ product.per_item|floatformat:2 }}</h2>
												<p>{% trans product.named_id context 'products' %}</p>
												<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</div>
									</div>
								</div>
							{% endfor %}
						</div>
					{% endfor %}
				{% endwith %}
			</div>
			 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
				<i class="fa fa-angle-left"></i>
			  </a>
			  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
				<i class="fa fa-angle-right"></i>
			  </a>
		</div>
	</div><!--/recommended_items-->
{% endblock %}

templates/default/_footer.html
{% load static %}
{% block footer %}
    <footer id="footer"><!--Footer-->
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="companyinfo">
                            <h2><span>e</span>-shopper</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="address">
                            <img src="{% static 'default/images/home/map.png' %}" alt="" />
                            <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-widget">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Service</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Online Help</a></li>
                                <li><a href="#">Contact Us</a></li>
                                <li><a href="#">Order Status</a></li>
                                <li><a href="#">Change Location</a></li>
                                <li><a href="#">FAQ’s</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Quock Shop</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">T-Shirt</a></li>
                                <li><a href="#">Mens</a></li>
                                <li><a href="#">Womens</a></li>
                                <li><a href="#">Gift Cards</a></li>
                                <li><a href="#">Shoes</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Policies</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Terms of Use</a></li>
                                <li><a href="#">Privecy Policy</a></li>
                                <li><a href="#">Refund Policy</a></li>
                                <li><a href="#">Billing System</a></li>
                                <li><a href="#">Ticket System</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>About Shopper</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Company Information</a></li>
                                <li><a href="#">Careers</a></li>
                                <li><a href="#">Store Location</a></li>
                                <li><a href="#">Affillate Program</a></li>
                                <li><a href="#">Copyright</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3 col-sm-offset-1">
                        <div class="single-widget">
                            <h2>About Shopper</h2>
                            <form action="#" class="searchform">
                                <input type="text" placeholder="Your email address" />
                                <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                                <p>Get the most recent updates from <br />our site and be updated your self...</p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © {% now "Y" %} E-SHOPPER Inc. All rights reserved.</p>
                </div>
            </div>
        </div>

    </footer><!--/Footer-->
{% endblock %}

templates/default/_header.html
{% load static %}
{% load i18n %}
{% block header %}
    <header id="header"><!--header-->
        <div class="header_top"><!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="#"><i class="fa fa-phone"></i> +1 (233) 456 78 90</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i> info@shop.com</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle"><!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="{% url 'index' %}"><img src="{% static 'default/images/home/logo.png' %}" alt="" /></a>
                        </div>
                        <div class="btn-group pull-right">
                            <div class="btn-group">
                                <button type="button" type="submit" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                    {{ LANGUAGE_CODE|upper }}
                                     <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    {% get_language_info_list for LANGUAGES as languages %}
                                    {% for language in languages %}
                                        <li><a href="/{{ language.code }}">{{ language.name_local }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                    DOLLAR
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Canadian Dollar</a></li>
                                    <li><a href="#">Euro</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                <!--<li><a href="{% url 'checkout' %}"><i class="fa fa-crosshairs"></i> Checkout</a></li>-->
                                {% with total_items=cart|length %}
                                    {% if cart|length > 0 %}
                                        <li><a href="{% url 'cart:detail' %}"><i class="fa fa-shopping-cart"></i> Your cart: {{ total_items }} goods {{ cart.get_total_price }}$</a></li>
                                        <!--{% trans 'Cart' context 'basic' %} -->
                                    {% else %}
                                        <li><a href="{% url 'all_products' %}"><i class="fa fa-shopping-cart"></i>Empty basket</a></li>
                                    {% endif %}
                                {% endwith %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom"><!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="{% url 'index' %}" class="active">Home</a></li>
                                <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="{% url 'all_products' %}">Products</a></li>
                                        <li><a href="{% url 'cart:detail' %}">Cart</a></li>
                                        <li><a href="{% url 'checkout' %}">Checkout</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'faq' %}">{% trans 'Faq' %}</a></li>
                                <li><a href="{% url 'testimonials' %}">{% trans 'Testimonials' %}</a></li>
                                <li><a href="{% url 'contact_us' %}">{% trans 'Contact US' %}</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="search_box pull-right">
                            <form action="{% url 'search' %}" method="GET">
                                <input type="text" placeholder="Search" name="q"/>
                                <button type="submit" class="btn btn-primary"> <i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->
{% endblock %}

templates/default/_left_sidebar.html
{% load static %}
{% load i18n %}
{% block left_sidebar %}
{% get_current_language as LANGUAGE_CODE %}
    <div class="left-sidebar">
        <h2>Category</h2>
        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            {% for category, products in menu.items %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#{{category}}">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                {% trans category context 'category' %}
                            </a>
                        </h4>
                    </div>
                    <div id="{{category}}" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                                {% for product in products %}
                                    <li><a href="/{{LANGUAGE_CODE}}/product/{{product}}">{% trans product context 'products' %}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div><!--/category-product-->

        <div class="shipping text-center"><!--shipping-->
            <img src="{% static 'default/images/home/shipping.jpg' %}" alt="" />
        </div><!--/shipping-->

    </div>
{% endblock %}

templates/default/_slider.html
{% load static %}
{% block slider %}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free E-Commerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'default/images/home/girl1.jpg' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'default/images/home/pricing.png' %}"  class="pricing" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>100% Responsive Design</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'default/images/home/girl2.jpg' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'default/images/home/pricing.png' %}"  class="pricing" alt="" />
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free Ecommerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'default/images/home/girl3.jpg' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'default/images/home/pricing.png' %}" class="pricing" alt="" />
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->
{% endblock %}